# my Second nginx pod
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  labels:
    app: nginx-server
    num: B
spec:
  containers:
  - name: nginx-server-2
    image: cmcreborn/nginx-test-002:0.0.1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html/
  volumes:
    - name: config-volume
      configMap:
        name: demo-configmap-html
