# my third nginx pod
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  labels:
    app: nginx-server
    num: C
spec:
  containers:
  - name: nginx-server-3
    image: cmcreborn/nginx-pod-3-hw:0.0.7
    ports:
    - containerPort: 5566
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "120Mi"
        cpu: "200m"
