# my web server pod
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  containers:
  - name: web-server
    image: cmcreborn/web-server-hw:0.0.1
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "120Mi"
        cpu: "200m"
